### ISSUE TITLE
[Android Bootcamp] InstagramClient-Project 1 (Gaetane Julmiste)

### ISSUE THREAD

**Issue by julmisteg** [julmisteg/CodePath-InstagramClient#1]
My app is complete. Please Review  ./cc @codepathreview @codepath

**Comment by cbaja** [comment]
Miss the goal.
- Where is the [video walkthorugh of your project. ](http://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments)
- the user story is not completed
- [code review](http://guides.codepath.com/android/Organizing-your-Source-Files)

@julmisteg

**Comment by julmisteg** [comment]
I tried adding the walkthrough  on the readme but it always showed a blank page .Thats what i added the walktought video in the project  @cbaja
